c1=str(input("Introduceti primul cuvant: "))
c2=str(input("Introduceti al doilea cuvant: "))
c3=str(input("Introduceti al treilea cuvant: "))
c4=str(input("Introduceti al patrula cuvant: "))
print(c1)
print(c2)
print(c3)
print(c4)
print(c1+" "+c2+" "+c3+" "+c4)